spring.application.name=droplet-api

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.data.mongodb.database=droplet
spring.data.mongodb.authentication-database=droplet