spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: droplet_user
      password: droplet_password
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/api/auth/google/callback
          github:
            redirect-uri: http://localhost:8080/api/auth/github/callback

token:
  state:
    ttl: 5
    providers:
      google:
        secret: ${GOOGLE_STATE_SECRET}
        issuer: droplet-oauth
        expiration-in-sec: 300
        leeway-in-sec: 10
      github:
        secret: ${GITHUB_STATE_SECRET}
        issuer: droplet-oauth
        expiration-in-sec: 300
        leeway-in-sec: 10
  jwt:
    secret: ${JWT_SESSION_SECRET}
    issuer: droplet
    expiration-in-sec: 3600
    leeway-in-sec: 30

management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-origins: http://localhost:5173
        allow-credentials: true

frontend:
  base-url: http://localhost:5173